name: Build docker images

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Check file changes
        run: git diff --name-only HEAD~1 HEAD | grep --perl-regexp '^[^\/]+' --only-matching > changes.txt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: deconvolution
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Singularity
        uses: eWaterCycle/setup-singularity@v7

      - name: Build docker images
        run: |
          set -e
          while IFS= read -r METHOD
          do
            if [ -f "$METHOD/Dockerfile" ]; then
              echo "Building $METHOD"
          
              docker buildx build \
                     --build-arg BASE_IMAGE=deconvolution/base:latest \
                     --tag deconvolution/${METHOD,,}:latest \
                     --cache-from=type=registry,ref=deconvolution/${METHOD,,}:buildcache \
                     --cache-to=type=registry,ref=deconvolution/${METHOD,,}:buildcache,mode=max \
                     --output=type=docker $METHOD
          
              if [[ "$METHOD" != "base" ]]; then
                if [[ && -f "$METHOD/.MATLAB" ]]; then
                  echo "$METHOD uses MATLAB and will not be tested"
                else
                  echo "Testing $METHOD using docker run"
                  docker run --rm -v `pwd`/data/bone-marrow.h5:/input.h5 -v `pwd`:/output -e INPUT_PATH=/input.h5 -e OUTPUT_PATH=/output/$METHOD-results.h5 deconvolution/${METHOD,,}:latest
            
                  if [ -f "$METHOD-results.h5" ]; then
                    echo "Found $METHOD-results.h5 for docker run"
            
                    echo "Testing $METHOD using singularity run"
                    singularity run --env INPUT_PATH=`pwd`/data/bone-marrow.h5 --env OUTPUT_PATH=`pwd`/$METHOD-results.h5 docker-daemon:deconvolution/${METHOD,,}:latest  
            
                    if [ -f "$METHOD-results.h5" ]; then
                      echo "Found $METHOD-results.h5 for singularity run"        
                    else
                      echo "$METHOD-results.h5 does not exist using singularity run."
                      exit 1
                    fi
                  else
                    echo "$METHOD-results.h5 does not exist using docker run."
                    exit 1
                  fi
                fi
              fi
          
              if [[ ${{github.ref}} == "master" ]]; then
                echo "Pushing $METHOD to docker hub"
                docker push deconvolution/${METHOD,,}:latest
              fi
            fi
          done < changes.txt
